import 'package:drift/drift.dart';
import 'package:flutter/material.dart';

enum Category {
  income,
  expense,
  savings,
  investment,
  loan,
  bank,
  salary,
  budget,
  shopping,
  food,
  transportation,
  bills,
  insurance,
  investmentStocks,
  investmentCrypto,
  debt,
  donation,
  entertainment,
  travel,
  healthcare,
  education,
  gift,
  subscription,
  houseRent,
  utilities,
  phoneBill,
  internetBill,
  tax,
  retirement,
  freelance,
  bonus,
  childcare,
  pet,
  clothing,
  electronics,
  luxury,
  others,
}

Map<Category, IconData> categoryIcon = {
  Category.income: Icons.attach_money,
  Category.expense: Icons.money_off,
  Category.savings: Icons.savings,
  Category.investment: Icons.trending_up,
  Category.loan: Icons.request_quote,
  Category.bank: Icons.account_balance,
  Category.salary: Icons.payments,
  Category.budget: Icons.account_balance_wallet,
  Category.shopping: Icons.shopping_cart,
  Category.food: Icons.fastfood,
  Category.transportation: Icons.directions_car,
  Category.bills: Icons.receipt,
  Category.insurance: Icons.health_and_safety,
  Category.investmentStocks: Icons.show_chart,
  Category.investmentCrypto: Icons.currency_bitcoin,
  Category.debt: Icons.credit_card,
  Category.donation: Icons.volunteer_activism,
  Category.entertainment: Icons.movie,
  Category.travel: Icons.flight,
  Category.healthcare: Icons.local_hospital,
  Category.education: Icons.school,
  Category.gift: Icons.card_giftcard,
  Category.subscription: Icons.subscriptions,
  Category.houseRent: Icons.home,
  Category.utilities: Icons.electrical_services,
  Category.phoneBill: Icons.phone,
  Category.internetBill: Icons.wifi,
  Category.tax: Icons.request_page,
  Category.retirement: Icons.emoji_people,
  Category.freelance: Icons.work,
  Category.bonus: Icons.card_membership,
  Category.childcare: Icons.child_care,
  Category.pet: Icons.pets,
  Category.clothing: Icons.shopping_bag,
  Category.electronics: Icons.devices,
  Category.luxury: Icons.diamond,
  Category.others: Icons.list,
};

Map<Category, Color> categoryColors = {
  Category.income: Colors.green,
  Category.expense: Colors.red,
  Category.savings: Colors.blue,
  Category.investment: Colors.purple,
  Category.loan: Colors.orange,
  Category.bank: Colors.blueGrey,
  Category.salary: Colors.greenAccent,
  Category.budget: Colors.teal,
  Category.shopping: Colors.pinkAccent,
  Category.food: Colors.orangeAccent,
  Category.transportation: Colors.cyan,
  Category.bills: Colors.amber,
  Category.insurance: Colors.indigo,
  Category.investmentStocks: Colors.deepPurple,
  Category.investmentCrypto: Colors.lightBlue,
  Category.debt: Colors.brown,
  Category.donation: Colors.pink,
  Category.entertainment: Colors.deepOrange,
  Category.travel: Colors.lightBlueAccent,
  Category.healthcare: Colors.redAccent,
  Category.education: Colors.deepOrangeAccent,
  Category.gift: Colors.purpleAccent,
  Category.subscription: Colors.blueAccent,
  Category.houseRent: Colors.greenAccent,
  Category.utilities: Colors.yellow,
  Category.phoneBill: Colors.blueGrey,
  Category.internetBill: Colors.lightGreen,
  Category.tax: Colors.redAccent,
  Category.retirement: Colors.lime,
  Category.freelance: Colors.cyanAccent,
  Category.bonus: Colors.green,
  Category.childcare: Colors.pinkAccent,
  Category.pet: Colors.orange,
  Category.clothing: Colors.purple,
  Category.electronics: Colors.blueGrey,
  Category.luxury: Colors.amberAccent,
  Category.others: Colors.grey,
};

class CategoryEnum extends TypeConverter<Category, String> {
  const CategoryEnum();

  @override
  Category fromSql(fromDb) =>
      Category.values.firstWhere((e) => e.name == fromDb);

  @override
  String toSql(Category value) => value.name;
}
