// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoQI7HX-cPQuKybrcbRxDlR4-bzE5TG_c',
    appId: '1:786728601432:android:10a0f76c3f19783521c72d',
    messagingSenderId: '786728601432',
    projectId: 'mono-f622a',
    databaseURL: 'https://mono-f622a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mono-f622a.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqnSlYHaAo5Vb-kMO-yNDKONaayDAzPs',
    appId: '1:786728601432:web:45251b0620522b3d21c72d',
    messagingSenderId: '786728601432',
    projectId: 'mono-f622a',
    authDomain: 'mono-f622a.firebaseapp.com',
    databaseURL: 'https://mono-f622a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mono-f622a.firebasestorage.app',
    measurementId: 'G-0YRV8KPBPV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwLegwf5Ws6GqMkBAuI_XsA429Z_a9RzI',
    appId: '1:786728601432:ios:1cce160b60d450a921c72d',
    messagingSenderId: '786728601432',
    projectId: 'mono-f622a',
    databaseURL: 'https://mono-f622a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mono-f622a.firebasestorage.app',
    iosBundleId: 'com.example.monoApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLegwf5Ws6GqMkBAuI_XsA429Z_a9RzI',
    appId: '1:786728601432:ios:1cce160b60d450a921c72d',
    messagingSenderId: '786728601432',
    projectId: 'mono-f622a',
    databaseURL: 'https://mono-f622a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mono-f622a.firebasestorage.app',
    iosBundleId: 'com.example.monoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdqnSlYHaAo5Vb-kMO-yNDKONaayDAzPs',
    appId: '1:786728601432:web:aca2503bf3006a7721c72d',
    messagingSenderId: '786728601432',
    projectId: 'mono-f622a',
    authDomain: 'mono-f622a.firebaseapp.com',
    databaseURL: 'https://mono-f622a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mono-f622a.firebasestorage.app',
    measurementId: 'G-17CKRJ190T',
  );

}